# fly.toml app configuration file generated for city-sim-web-full on 2025-08-18T14:51:32+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'city-sim-web-full'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[mounts]]
  source      = "data"
  destination = "/data"